### ISSUE TITLE
Command doesn't copy to clipboard

### ISSUE THREAD

**Issue by dwelle** [bpasero/copy-path-relative-posix#1]
Doing either

- `ctrl + p` → `Copy Relative Path (POSIX)`,
- or binding to a hotkey and pressing it

doesn't store the path of currently opened file to clipboard at all.

Version: 1.39.2 (system setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by bpasero** [comment]
Thanks, I am now falling back to the active editor path when using `Cmd+P` or keybinding.

**Comment by bpasero** [comment]
Published version `0.0.4`.

**Comment by dwelle** [comment]
Working great, thanks!
